Test for `flaky.js` (#227)

diff --git a/.github/workflows/changes-tested.yml b/.github/workflows/changes-tested.yml
--- a/.github/workflows/changes-tested.yml
+++ b/.github/workflows/changes-tested.yml
@@ -18,14 +18,26 @@ jobs:
       uses: dorny/paths-filter@v4
       with:
         filters: |
-          code:
+          py-code:
             - 'src/**/*.py'
-          tests:
+          py-tests:
             - 'src/tests/**/*.py'
+          js-code:
+            - 'src/gui/static/js/**/*.js'
+            - '!src/gui/static/js/**/*.test.js'
+          js-tests:
+            - 'src/gui/static/js/**/*.test.js'
 
-    - name: Ensure code changes have corresponding tests
-      if: steps.filter.outputs.code == 'true' && steps.filter.outputs.tests != 'true'
+    - name: Ensure Python code changes have corresponding tests
+      if: steps.filter.outputs.py-code == 'true' && steps.filter.outputs.py-tests != 'true'
       run: |
-        echo "Error: Code changes detected, but no test files were modified."
+        echo "Error: Python code changes detected, but no test files were modified."
+        exit 1
+      shell: bash
+
+    - name: Ensure JS code changes have corresponding tests
+      if: steps.filter.outputs.js-code == 'true' && steps.filter.outputs.js-tests != 'true'
+      run: |
+        echo "Error: JS code changes detected, but no JS test files were modified."
         exit 1
       shell: bash
